[project]
name = "a4-mcda-5511"
version = "0.1.0"
description = "A4 for MCDA 5511"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "scikit-learn>=1.6.1",
    "torch>=2.6.0",
    "torchvision>=0.21.0",
    "transformers>=4.50.2",
]
